name: build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: cmake -B build
      - run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          path: build/Release/volume-locker.exe
